### ISSUE TITLE
Filter / KQL search causes some viz to show nothing

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#27]
I used a search / filter to see data in the dashboard that matches the query. In this case it was to look at a country or continent like this:
`geoip.continent_code:AS`

**To Reproduce**
1. DNS Pihole dashbaord
2. Select a time from like Last 90 days
3. Put in a query like `geoip.continent_code:AS` as KQL
4. Notice that some the visualizations show no values or are empty
- Requests vs piholed - pihole (empty)
- DNS requests total - pihole = 0 DNS Requests

**Expected behavior**
The viz should show the counts or the values that match the filter

**Screenshots**
![geoip_query_viz_no_values](https://user-images.githubusercontent.com/955527/68974672-8842bb00-07ae-11ea-8714-cc2188000835.png)

**Comment by nin9s** [comment]
the problem is that the geo fields are populated depending on the RESPONSE not the REQUEST so we dont see the geo_ip details in the request queries. there is no information about an ip address in the request for what we can do a geo_ip query.

I need to find out if we can add the geo_ip fields to the request log lines _after_ we have received the response. AnyThoughts?

**Comment by nin9s** [comment]
fortunately logstashs geo_ip plugin can handle both an ip and a hostname so it was easier I tought :)

have a look at https://github.com/nin9s/elk-hole/blob/ec76d1076945e75eddf3158e5688cbf378e95217/logstash/conf.d/20-dns-syslog.conf

note that everything related to beeing resolved as piholed/0.0.0.0 will not make sense to be processed as geoip

**Comment by nin9s** [comment]
@aviationfan fixed? can we close this?

**Comment by aviationfan** [comment]
Yes we can close this
