### ISSUE TITLE
Log entries with full URL instead of domain causing grokparsefailure

### ISSUE THREAD

**Issue by aviationfan** [nin9s/elk-hole#34]
I see some log entries that fail to parse and what makes them different is the presence of a complete URL in the log. I am pretty sure that the previous versions of pihole did not have any entries with http(s) in them and now they do.

**To Reproduce**
The samples provided came from an iPad and not which app or site produced the calls to 
`https://app-measurement.com/sdk-exp`

**Expected behavior**
A grok pattern that possibly parses out the domain from the URL. I have no reason to add a field with URL when the domain is what we all really care about.

**Sample log entries with URLs**
```
Jun  1 16:15:42 dnsmasq[1552]: 12845 192.168.1.162/53431 forwarded https://app-measurement.com/sdk-exp to 208.67.222.222
Jun  1 16:15:42 dnsmasq[1552]: 12845 192.168.1.162/53431 reply https://app-measurement.com/sdk-exp is NXDOMAIN
Jun  1 16:15:42 dnsmasq[1552]: 12845 192.168.1.162/53431 query[A] https://app-measurement.com/sdk-exp from 192.168.1.162
Jun  1 16:15:42 dnsmasq[1552]: 12845 192.168.1.162/53431 forwarded https://app-measurement.com/sdk-exp to 208.67.222.222
```

**Desktop (please complete the following information):**
 - OS: macOS, iOS, Android, Linux

**Pihole version 5.0**

**Comment by nin9s** [comment]
hm I've sometimes seen this in the past (also before 5.0) but in my oppinion this is just incorrect behavior of the application sending a url instead of a domain name in the dns request (for some strange reason). 

We can filter out the https:// portion and everything beginning from the following "/"  but that wouldnt be representative as these queries never get answered at all (NXDOMAIN sent back to the client). 

by the way I have these queries to from my ipad:
![image](https://user-images.githubusercontent.com/17455046/83751042-7c451a80-a666-11ea-8e2d-dcbe3ecc85c7.png)

For me its just incorrect behavior of the application generating the request

**Comment by nin9s** [comment]
@aviationfan see and let me know if this suits your wish: https://github.com/nin9s/elk-hole/pull/28/files

please dont forget to ommit the output section or change to your host before

**Comment by aviationfan** [comment]
This is a great, thank you for looking at it.
